library(oce)
file <- "adp_rdi.000"
adp <- read.adp.rdi(file, debug=3)
str(adp[["metadata"]])
str(adp[["data"]])
cat("time\n")
print(adp[["time"]])
cat("soundSpeed\n")
print(adp[["soundSpeed"]])
cat("heading\n")
print(adp[["heading"]])
cat("pitch\n")
print(adp[["pitch"]])
cat("roll\n")
print(adp[["roll"]])

print(dim(adp[["v"]]))
print(adp[["v"]][1,,])
