using NCDatasets
using Dates
using DataFrames
using Downloads
using GibbsSeaWater
using GMT: gmtread
using Interpolations
using Plots
using Printf
using CSV
using Dierckx
using Statistics
using StatsBase
using TiffImages

# Types
export OA # the base from which the folowing inherit
export Adp
export Amsr
export Argo
export Ctd
export Coastline
export Dem
export Echosounder
export Glider
export Nonna
export Section
export Topography

# Functions
export add_freezing_curve!
export as_section
export beam_to_xyz
export bin_mean
export CT
export depth_from_pressure
export despike
export drop_qc
export geod_distance
export get_erddap_index
export get_file
export get_nc_value
export get_section
export grid_section
export handle_qc
export handle_qc!
export interpolate_barnes
export label_from_varname
export MLD_CF
export MLD_CF_detailed
export MLD_KRH
export ILD_KRH
export N2
export N2_spline
export N2_first_difference
export plot_adp
export plot_dem
export plot_echosounder
export plot_profile
export plot_section
export plot_stations
export plot_TS
export plot_TS_sigma0_contours
export plot_TS_spiciness0_contours
export pressure_from_depth
export pressure_from_z
export read_adp_rdi
export read_dem
export read_echosounder
export read_glider
export read_nonna
export read_section
export rename_data
export running_mean
export running_median
export salinity_from_conductivity
export SA
export section_is_gridded
export subset_dem
export xyz_to_enu
export z_from_pressure
