using NCDatasets
using Dates
using DataFrames
using Downloads
using GibbsSeaWater
using GMT: gmtread
using Interpolations
using Plots
using Printf
using CSV
using Dierckx
using Statistics
using StatsBase
using TiffImages

# Types
export OA # the base from which the folowing inherit
export Adp
export Amsr
export Argo
export Ctd
export Coastline
export Dem
export Echosounder
export Glider
export Nonna
export Section
export Topography

# Functions
export argo_id_cycle
export as_ctd
export as_section
export beam_to_xyz
export bin_mean
export coastline
export coordinate_from_string
export coriolis
export CT
export debug
export depth_from_pressure
export despike
export drop_qc
export fix_gsw_bad_code
export fix_gsw_bad_code!
export geod_distance
export get_amsr
export get_argo_index
export get_argo
export get_element
export get_file
export get_nc_value
export get_section
export get_topography
export gravity
export grid_ctd
export grid_section
export handle_qc
export handle_qc!
export interpolate_barnes
export label_from_varname
export MLD_CF
export MLD_CF_detailed
export MLD_KRH
export ILD_KRH
export N2
export N2_spline
export N2_first_difference
export oad
export plot_adp
export plot_amsr
export plot_coastline
export plot_coastline!
export plot_dem
export plot_echosounder
export plot_profile
export plot_section
export plot_stations
export plot_topography
export plot_TS
export plot_TS_sigma0_contours
export plot_TS_spiciness0_contours
export pressure_from_depth
export pressure_from_z
export pretty
export read_adp_rdi
export read_amsr
export read_argo
export read_argo_index
export read_ctd_cnv
export read_ctd_exchange
export read_ctd_rsk
export read_dem
export read_echosounder
export read_glider
export read_nonna
export read_section
export read_topography
export rename_data
export running_mean
export running_median
export salinity_from_conductivity
export SA
export scale_bar
export section_is_gridded
export set_teos
export six_num
export station_map
export subset_amsr
export subset_ctd
export subset_ctd!
export subset_dem
export summarize
export summarize_argo_data_tests
export T90_from_T48
export T90_from_T68
export toc
export xyz_to_enu
export z_from_pressure

