using NCDatasets
using Dates
using DataFrames
using Downloads
using GibbsSeaWater
using Interpolations
using Plots
using Printf
using CSV
using Dierckx
using Statistics
using TiffImages

# Types
export OA
export Adp
export Amsr
export Argo
export Ctd
export Coastline
export Section
export Topography

# Functions
export argo_id_cycle
export as_ctd
export as_section
export beam_to_xyz
export coastline
export coordinate_from_string
export coriolis
export CT
export depth_from_pressure
export fix_gsw_bad_code
export fix_gsw_bad_code!
export geod_distance
export get_amsr
export get_argo_index
export get_argo
export get_element
export get_file
export get_nc_value
export get_section
export get_topography
export gravity
export grid_ctd
export grid_section
export N2
export plot_adp
export plot_amsr
export plot_coastline
export plot_coastline!
export plot_echosounder
export plot_profile
export plot_section
export plot_stations
export plot_topography
export plot_TS
export pressure_from_depth
export pressure_from_z
export pretty
export read_adp_rdi
export read_amsr
export read_argo
export read_argo_index
export read_ctd_cnv
export read_ctd_exchange
export read_ctd_rsk
export read_echosounder
export read_section
export read_topography
export rename_data
export salinity_from_conductivity
export SA
export scale_bar
export section_is_gridded
export set_teos
export station_map
export subset_amsr
export subset_ctd
export subset_ctd!
export summarize
export T90_from_T48
export T90_from_T68
export toc
export xyz_to_enu
export z_from_pressure

