name: Documentation

on:
  push:
    branches:
      - main # update to match your development branch (master, main, dev, trunk, ...)
    tags: '*'
  pull_request:

jobs:
  build:
    # These permissions are needed to:
    # - Deploy the documentation: https://documenter.juliadocs.org/stable/man/hosting/#Permissions
    # - Delete old caches: https://github.com/julia-actions/cache#usage
    permissions:
      actions: write
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - uses: julia-actions/cache@v2
      # START (workaround for failing GH action)
      - name: Remove General registry (if exists)
        run: julia -e 'using Pkg; try Pkg.Registry.rm("General") catch end'
      - name: Add General registry
        run: julia -e 'using Pkg; Pkg.Registry.add("General")'
      # END
      - uses: julia-actions/julia-buildpkg@v1
      - name: Build documentation
        run: |
          julia --project=docs/ -e '
            using Pkg
            Pkg.add("Documenter")
            Pkg.add("Plots")
            if !haskey(Pkg.project().dependencies, "OceanAnalysis")
                Pkg.develop(PackageSpec(path=pwd()))
            end
            Pkg.instantiate()'
          julia --project=docs/ docs/make.jl        
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
